//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bao_Hanh
    {
        public string id_BaoHanh { get; set; }
        public string lim_BaoHanh { get; set; }
        public string descript { get; set; }
    }
}
