//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HoaDon
    {
        public string id_DanhMuc { get; set; }
        public string id_HoaDon { get; set; }
        public Nullable<int> num_HoaDon { get; set; }
        public Nullable<int> total_HoaDon { get; set; }
    }
}
