//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public string id_DanhMuc { get; set; }
        public string name_DanhMuc { get; set; }
        public string size_DanhMuc { get; set; }
        public string engine_DanhMuc { get; set; }
        public string volume_DanhMuc { get; set; }
        public string breakfont_DanhMuc { get; set; }
        public string breakend_DanhMuc { get; set; }
        public string tire_DanhMuc { get; set; }
        public string torque_DanhMuc { get; set; }
        public string id_HangSX { get; set; }
        public string id_LoaiSP { get; set; }
        public string id_BaoHanh { get; set; }
        public Nullable<int> weight_DanhMuc { get; set; }
        public Nullable<int> price_DanhMuc { get; set; }
        public byte[] image_DanhMuc { get; set; }
        public Nullable<int> total_DanhMuc { get; set; }
    }
}
