//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hang_SX
    {
        public string id_HangSX { get; set; }
        public string name_HangSX { get; set; }
        public string descrip_HangSX { get; set; }
    }
}
