//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string id_HoaDon { get; set; }
        public Nullable<System.DateTime> date_HoaDon { get; set; }
        public string phone_HoaDon { get; set; }
        public string name_HoaDon { get; set; }
        public string email_HoaDon { get; set; }
        public string address_HoaDon { get; set; }
    }
}
