//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai_SP
    {
        public string id_LoaiSP { get; set; }
        public string name_LoaiSP { get; set; }
        public string descrip_LoaiSP { get; set; }
    }
}
