//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public string id_NhaCC { get; set; }
        public string name_NhaCC { get; set; }
        public string phone_NhaCC { get; set; }
        public string email_NhaCC { get; set; }
        public string address_NhaCC { get; set; }
    }
}
