//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string id_SanPham { get; set; }
        public string sokhung_SanPham { get; set; }
        public string somay_SanPham { get; set; }
        public string descript_SanPham { get; set; }
    }
}
