//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_TaiKhoan
    {
        public string user_Acc { get; set; }
        public string name_User { get; set; }
        public string email_User { get; set; }
        public string phone_User { get; set; }
        public string address_User { get; set; }
    }
}
